apiVersion: v1
kind: Service
metadata:
  name: yt-flask-svc
  namespace: kagent
spec:
  type: NodePort
  selector:
    app: yt-flask
  ports:
    - name: http
      port: 80
      targetPort: 5000
      nodePort: 32000
