apiVersion: v1
kind: Secret
metadata:
  name: openai-gpt-4o
  namespace: kagent
type: Opaque
stringData:
  OPENAI_API_KEY: "INSERT_YOUR_API_KEY"
---
apiVersion: kagent.dev/v1alpha2
kind: ModelConfig
metadata:
  name: openai-gpt-4o
  namespace: kagent
spec:
  apiKeySecret: openai-gpt-4o
  apiKeySecretKey: OPENAI_API_KEY
  model: gpt-4o
  provider: OpenAI
  openAI:
    temperature: "0.3"
    timeout: 300
    
